/* SAMPLE APEX DATA
var apex_fg300 = [0,
    new ApexGeneral(1,50,0,0,"linaTetris"),
    new ApexGeneral(2,80,0,0,"linaTetris"),
    new ApexGeneral(3,90,30,0,"linaTetris"),
    new ApexGeneral(4,100,30,0,"linaTetris"),
    new ApexGeneral(5,150,30,150,"linaTetris"),
    new ApexGeneral(6),
    new ApexGeneral(7,250,30,150,"linaTetris"),
    new ApexGeneral(8,270,40,200,"linaTetris",[[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2]),new ApexUpgrade("Sympathetic Detonation", ["+18% chance for +36% Crit damage"], [2])],[],[]]),
    new ApexGeneral(9,270,40,200,"linaTetris",[[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2]),new ApexUpgrade("Sympathetic Detonation", ["+18% chance for +36% Crit damage"], [2])],[],[]]),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_sample = [0,
    new ApexGeneral(1),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];
*/

/* SAMPLE SUPERCAP DATA
this sample is from ST59, which has 3 mods per M,A,B,C slot.

    new ApexSuperCap(8, 69420, 0, 50, "Fake News", [ 
        [[],[],[]] ,  
        [[],[],[]] , 
        [ [new ApexUpgrade("Nuclear Tipped Missiles", ["+1000 DPH to Melon Launcher"], [12])] , [] , [] ],
        [ [] , [new ApexUpgrade("Reinforced Structure", ["+1% HP"], [2])] , [new ApexUpgrade("Explosive Reactive Armor", ["+15 Physical Resistance"], [2])] ] 
    ]),
*/

/*
----- Scratchpad -----
Light Cone A missing!
new ApexGeneral(15,16000,10,100,"JackCross", [
    [new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],
    [new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],
    [new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]
    ]),

Callisto C missing!
new ApexGeneral(10, 110??, 10, 50, "JackCross", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Warhead Modification", ["+7 DPH on MK2-AT-8-700 Cluster Torpedo"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Generic Battery System"], [2]],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Warhead Modification", ["+52 DPH on MK2-AT-8-720A Heavy Torpedo"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Generic Battery System"], [2]],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("<strong>Unknown upgrades! Contact linaTetris</strong>", ["<strong>Unknown! If you have Callisto C apexed, you may contribute!</strong>"], ["???"])]])






*/
var apex_fg300 = [0,
    new ApexGeneral(1, 145, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_mare_i = [0,
    new ApexGeneral(1,200,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3, 595, 0, 0, "boss6651", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4, 795, 0, 0, "boss6651", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5, 1105, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6, 1300, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_mare_t = [0,
    new ApexGeneral(1,170,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_mare_s = [0,
    new ApexGeneral(1,205,0,0,"linaTetris"),
    new ApexGeneral(2,410,0,0,"boss6651"),
    new ApexGeneral(3, 615, 0, 0, "boss6651", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_mare_n = [0,
    new ApexGeneral(1,125,0,0,"linaTetris"),
    new ApexGeneral(2,250,0,0,"linaTetris"),
    new ApexGeneral(3,375,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4),
    new ApexGeneral(5, 690, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6, 815, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_xeno = [0,
    new ApexGeneral(1,145,0,0,"linaTetris"),
    new ApexGeneral(2,290,0,0,"linaTetris"),
    new ApexGeneral(3,435,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4,580,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5, 805, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6, 950, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_ino = [0,
    new ApexGeneral(1),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_ruby = [0,
    new ApexGeneral(1,230,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5, 1260, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])], [new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6, 1485, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])], [new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_m470 = [0,
    new ApexGeneral(1,195,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4, 770, 0, 0, "boss6651", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5, 1070, 0, 50, "boss6651", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_carilion = [0,
    new ApexGeneral(1,115,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_reliat = [0,
    new ApexGeneral(1,145,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_zircon = [0,
    new ApexGeneral(1,185,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13, 2590, 10, 50, "JackCross", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP", "+4% HP"], [2,2,2,2]), new ApexUpgrade("Airborne Weapon Modification", ["+4% DPH on Drifter corvettes"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+9% chance for +15% Crit damage on SG-1080 battery system"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP", "+4% HP"], [2,2,2,2]), new ApexUpgrade("Airborne Weapon Maintenance", ["+4% DPH on Drifter corvettes"], [2]), new ApexUpgrade("Gauss Coil Enhancement", ["+20 DPH on BR-1400A railgun"], [2])]]),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

// destroyers

var apex_ac721 = [0,
    new ApexGeneral(1,470,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5, 2600, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6, 3065, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_eris = [0,
    new ApexGeneral(1,420,0,0,"linaTetris"),
    new ApexGeneral(2,840,0,0,"linaTetris"),
    new ApexGeneral(3,1255,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4,1675,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5, 2325, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6, 2745, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(7, 3160, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(8, 3580, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2])]]),
    new ApexGeneral(9),
    new ApexGeneral(10, 4650, 10, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Barrel Enhancement", ["+3 DPH on AG-1208 \"Eris\""], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Barrel Enhancement", ["+10 DPH on AG-2300 \"Ashes of Eris\""], [2]), new ApexUpgrade("Ammo Enhancement", ["+1 DPH on AG-1156 \"Eris\""], [2])], [new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Barrel Enhancement", ["+3 DPH on AG-1208 \"Eris\""], [2])]]),
    new ApexGeneral(11, 5065, 10, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Barrel Enhancement", ["+3 DPH on AG-1208 \"Eris\""], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Barrel Enhancement", ["+10 DPH on AG-2300 \"Ashes of Eris\""], [2]), new ApexUpgrade("Ammo Enhancement", ["+1 DPH on AG-1156 \"Eris\""], [2])], [new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Barrel Enhancement", ["+3 DPH on AG-1208 \"Eris\""], [2])]]),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_ceres = [0,
    new ApexGeneral(1,445,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5, 2460, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6, 2905, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_quaoar = [0,
    new ApexGeneral(1,420,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_taurus = [0,
    new ApexGeneral(1,495,0,0,"linaTetris"),
    new ApexGeneral(2,990,0,0,"linaTetris"),
    new ApexGeneral(3,1480,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4,1975,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5, 2745, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6), // possibly 3235 HP?
    new ApexGeneral(7, 3730, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(8, 4225, 0, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2])]]),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_tundra = [0,
    new ApexGeneral(1,565,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10, 6270, 0, 50, "JackCross", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Enhance Repair Beam", ["+2% Repair Effectiveness"], [2]), new ApexUpgrade("Enhance Repair Materials", ["+2% Repair Effectiveness"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Rapid-Fire Battery System"], [2])], [new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Airborne Ammo Enhancement", ["+2% Damage for loaded aircraft"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Integrated Armory"], [2])]]),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_aldabra = [0,
    new ApexGeneral(1,510,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_guardian = [0,
    new ApexGeneral(1,355,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_hussar = [0,
    new ApexGeneral(1,315,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3,935,0,0,"boss6651", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4,1245,0,0,"boss6651", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_fluorite = [0,
    new ApexGeneral(1,385,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_helios = [0,
    new ApexGeneral(1),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_vanguard = [0,
    new ApexGeneral(1,315,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

// cruisers

var apex_kccpv = [0,
    new ApexGeneral(1,715,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_cas = [0,
    new ApexGeneral(1,980,0,0,"linaTetris"),
    new ApexGeneral(2,1960,0,0,"linaTetris"),
    new ApexGeneral(3,2940,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4,3920,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5,5450,0,50,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])]]),
    new ApexGeneral(6,6430,0,50,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_callisto = [0, // apex 10 is incomplete!
    new ApexGeneral(1,1090,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    // new ApexGeneral(10, 4650, 10, 50, "linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Warhead Modification", ["+7 DPH on MK2-AT-8-700 Cluster Torpedo"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Generic Battery System"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Warhead Modification", ["+52 DPH on MK2-AT-8-720A Heavy Torpedo"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Generic Battery System"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("<strong>Unknown upgrades! Contact linaTetris</strong>", ["<strong>Unknown! If you have Callisto C apexed, you may contribute!</strong>"], ["??"])]]),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_io = [0,
    new ApexGeneral(1,850,0,0,"linaTetris"),
    new ApexGeneral(2,1700,0,0,"linaTetris"),
    new ApexGeneral(3,2550,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4,3400,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5,4730,0,50,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])]]),
    new ApexGeneral(6,5580,0,50,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])]]),
    new ApexGeneral(7,6430,0,50,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])]]),
    new ApexGeneral(8,7280,0,50,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2])]]),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_conamara = [0,
    new ApexGeneral(1,980,0,0,"linaTetris"),
    new ApexGeneral(2,1960,0,0,"linaTetris"),
    new ApexGeneral(3,2940,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4,3920,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5,5450,0,50,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])]]),
    new ApexGeneral(6,6430,0,50,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_chimera = [0,
    new ApexGeneral(1,1225,0,0,"linaTetris"),
    new ApexGeneral(2,2450,0,0,"linaTetris"),
    new ApexGeneral(3,3670,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_lightcone = [0,
    new ApexGeneral(1,955,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3,2860,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(4,3810,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15), // JackCross has it but LC A stats missing.
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_jaeger = [0,
    new ApexGeneral(1,1045,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4,4170,0,0,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5,5800,0,50,"linaTetris", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP","+2% HP"], [2,2])]]),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_predator = [0,
    new ApexGeneral(1,1045,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10, 11595, 10, 50, "JackCross", [[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Projectile Weapon System"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Defensive Battery System"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Airborne Weapon Maintenance", ["+2% damage for loaded aircraft"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Defensive Battery System"], [2])],[new ApexUpgrade("Kernel Structure Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Anti-Aircraft Missile System"], [2]), new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage on Defensive Battery System"], [2])]]),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_ranger = [0,
    new ApexGeneral(1,1005,0,0,"linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];


var apex_st59 = [0,
    new ApexSuperCap(1,2190,0,0,"linaTetris"),
    new ApexSuperCap(2),
    new ApexSuperCap(3),
    new ApexSuperCap(4),
    new ApexSuperCap(5),
    new ApexSuperCap(6),
    new ApexSuperCap(7, 21780, 0, 50, "Atrophos", [ [[],[],[]] ,  [ [],[],[] ] , [ [new ApexUpgrade("Warhead Modification", ["+5 DPH to Melon Launcher"], [2])] , [new ApexUpgrade("Airborne Weapon Maintenance", ["+1% Damage for loaded aircraft"], [2])] , [] ], [ [] , [] , [] ] ]),
    new ApexSuperCap(8),
    // new ApexSuperCap(8, 69420, 0, 50, "Fake News", [ [[],[],[]] ,  [ [],[],[] ] , [ [new ApexUpgrade("Nuclear Tipped Missiles", ["+1000 DPH to Melon Launcher"], [12])] , [] , [] ], [ [] , [new ApexUpgrade("Reinforced Structure", ["+1% HP"], [2])] , [new ApexUpgrade("Explosive Reactive Armor", ["+15 Physical Resistance"], [2])] ] ]),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];


var apex_es = [0,
    new ApexSuperCap(1,2350,0,0,"linaTetris"),
    new ApexSuperCap(2),
    new ApexSuperCap(3),
    new ApexSuperCap(4),
    new ApexSuperCap(5),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    // new ApexSuperCap(8, 69420, 0, 50, "Fake News", [ [[],[]] , [ [new ApexUpgrade("Nuclear Tipped Missiles", ["+1000 DPH to Supernova Torpedo every 2 rounds"], [25])] , [new ApexUpgrade("Nuclear Tipped Missiles", ["+1000 DPH to Supernova Torpedo every 2 rounds"], [25])] , [new ApexUpgrade("Fusion Powered Missiles", ["+1000 DPH to Supernova Torpedo every 2 rounds"], [25])] ], [[],[]], [[],[],[]], [[],[]] ]),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_sou = [0,
    new ApexSuperCap(1,2890,0,0,"linaTetris"),
    new ApexSuperCap(2,6745,0,0,"linaTetris"),
    new ApexSuperCap(3,10600,0,0,"linaTetris"),
    new ApexSuperCap(4,14455,0,0,"linaTetris"),
    new ApexSuperCap(5,21085,0,50,"linaTetris"),
    new ApexSuperCap(6,24940,0,50,"linaTetris"),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_sop = [0,
    new ApexSuperCap(1,2975,0,0,"linaTetris"),
    new ApexSuperCap(2),
    new ApexSuperCap(3),
    new ApexSuperCap(4),
    new ApexSuperCap(5),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_ctg = [0,
    new ApexSuperCap(1,2270,0,0,"linaTetris"),
    new ApexSuperCap(2),
    new ApexSuperCap(3),
    new ApexSuperCap(4,11340,0,0,"linaTetris"),
    new ApexSuperCap(5,16535,0,50,"linaTetris"),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_swordbearer = [0,
    new ApexSuperCap(1),
    new ApexSuperCap(2),
    new ApexSuperCap(3),
    new ApexSuperCap(4),
    new ApexSuperCap(5),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_tb = [0,
    new ApexSuperCap(1,2350,0,0,"linaTetris"),
    new ApexSuperCap(2),
    new ApexSuperCap(3),
    new ApexSuperCap(4),
    new ApexSuperCap(5),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_cv3k = [0,
    new ApexSuperCap(1,4460,0,0,"linaTetris"),
    new ApexSuperCap(2,10405,0,0,"linaTetris"),
    new ApexSuperCap(3,16350,0,0,"linaTetris"),
    new ApexSuperCap(4),
    new ApexSuperCap(5,32515,0,50,"linaTetris"),
    new ApexSuperCap(6,38460,0,50,"linaTetris"),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_eh = [0,
    new ApexSuperCap(1,4785,0,0,"linaTetris"),
    new ApexSuperCap(2),
    new ApexSuperCap(3,17545,0,0,"Orwell"),
    new ApexSuperCap(4,23925,0,0,"Orwell"),
    new ApexSuperCap(5,34890,0,50,"Orwell"),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_sw = [0,
    new ApexSuperCap(1,5275,0,0,"linaTetris"),
    new ApexSuperCap(2,12315,0,0,"linaTetris"),
    new ApexSuperCap(3,19350,0,0,"linaTetris"),
    new ApexSuperCap(4),
    new ApexSuperCap(5),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_crux = [0,
    new ApexSuperCap(1,4460,0,0,"linaTetris"),
    new ApexSuperCap(2,10405,0,0,"linaTetris"),
    new ApexSuperCap(3,16350,0,0,"linaTetris"),
    new ApexSuperCap(4),
    new ApexSuperCap(5,32515,0,50,"linaTetris"),
    new ApexSuperCap(6,38460,0,50,"linaTetris"),
    new ApexSuperCap(7,44405,0,50,"linaTetris", [[[],[]], [[],[]], [[],[]], [[new ApexUpgrade("Airborne Weapon Maintenance", ["+1% Damage for loaded aircraft"], [2])],[new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage"], [2])],[]]]),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10,66515,10,50,"linaTetris", [[[new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage"], [2])],[new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage"], [2])]], [[new ApexUpgrade("Airborne Weapon Maintenance", ["+1% Damage for loaded aircraft"], [2])],[new ApexUpgrade("Airborne Weapon Maintenance", ["+1% Damage for loaded aircraft"], [2])]], [[],[]], [[new ApexUpgrade("Airborne Weapon Maintenance", ["+1% Damage for loaded aircraft"], [2])],[new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage"], [2])],[]]]),
    new ApexSuperCap(11,72465,10,50,"linaTetris", [[[new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage"], [2])],[new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage"], [2])]], [[new ApexUpgrade("Airborne Weapon Maintenance", ["+1% Damage for loaded aircraft"], [2])],[new ApexUpgrade("Airborne Weapon Maintenance", ["+1% Damage for loaded aircraft"], [2])]], [[],[]], [[new ApexUpgrade("Airborne Weapon Maintenance", ["+1% Damage for loaded aircraft"], [2])],[new ApexUpgrade("Sympathetic Detonation", ["+6% chance for +12% Crit damage"], [2])],[]]]),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_fsv = [0,
    new ApexSuperCap(1,2890,0,0,"linaTetris"),
    new ApexSuperCap(2),
    new ApexSuperCap(3),
    new ApexSuperCap(4),
    new ApexSuperCap(5),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_ediacaran = [0,
    new ApexSuperCap(1,3850,0,0,"linaTetris"),
    new ApexSuperCap(2),
    new ApexSuperCap(3),
    new ApexSuperCap(4),
    new ApexSuperCap(5),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];

var apex_warspite = [0,
    new ApexSuperCap(1,4565,0,0,"PremTech"),
    new ApexSuperCap(2),
    new ApexSuperCap(3),
    new ApexSuperCap(4),
    new ApexSuperCap(5),
    new ApexSuperCap(6),
    new ApexSuperCap(7),
    new ApexSuperCap(8),
    new ApexSuperCap(9),
    new ApexSuperCap(10),
    new ApexSuperCap(11),
    new ApexSuperCap(12),
    new ApexSuperCap(13),
    new ApexSuperCap(14),
    new ApexSuperCap(15),
    new ApexSuperCap(16),
    new ApexSuperCap(17),
    new ApexSuperCap(18),
    new ApexSuperCap(19),
    new ApexSuperCap(20)
];


// corvettes

var apex_cvii003 = [0,
    new ApexGeneral(1, 70, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_cvm011 = [0,
    new ApexGeneral(1, 105, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_t800 = [0,
    new ApexGeneral(1, 105, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17, 1930, 0, 0, "JackCross", [[new ApexUpgrade("Aircraft Armor Enhancement", ["+1% HP", "+2% HP", "+3% HP", "+4% HP"], [2,2,2,2]), new ApexUpgrade("Enhance Recharge Power", ["+2% Pulse Cannon Damage", "+4% Pulse Cannon Damage"], [2,2])]]),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_levy = [0,
    new ApexGeneral(1, 85, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_bopp = [0,
    new ApexGeneral(1, 100, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_tempel = [0,
    new ApexGeneral(1),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_rb7 = [0,
    new ApexGeneral(1, 75, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_ass = [0,
    new ApexGeneral(1, 75, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_cell = [0,
    new ApexGeneral(1, 95, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    // MISSING CRIT DAMAGE DETAILS: new ApexGeneral(11, 1105, 0, 0, "Zero Phoenix", [[new ApexUpgrade("Aircraft Armor Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Warhead Modification", ["+3 DPH on CT-4-4500 \"Beehive\""], [2])]]),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_nebula = [0,
    new ApexGeneral(1, 90, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_void = [0,
    new ApexGeneral(1, 75, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_wildfire = [0,
    new ApexGeneral(1),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_sc002 = [0,
    new ApexGeneral(1, 40, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_at021 = [0,
    new ApexGeneral(1, 70, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_br050 = [0,
    new ApexGeneral(1, 70, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_stingray = [0,
    new ApexGeneral(1, 75, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_janbiya = [0,
    new ApexGeneral(1, 60, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_newland = [0,
    new ApexGeneral(1, 65, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_spore = [0,
    new ApexGeneral(1, 50, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_bullfrog = [0,
    new ApexGeneral(1, 65, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_sandrake = [0,
    new ApexGeneral(1, 60, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_strix = [0,
    new ApexGeneral(1, 70, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3, 205, 0, 50, "boss6651", [[new ApexUpgrade("Aircraft Armor Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(3, 70, 0, 50, "boss6651", [[new ApexUpgrade("Aircraft Armor Enhancement", ["+1% HP"], [2])]]),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_vb = [0,
    new ApexGeneral(1, 85, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5, 450, 0, 50, "linaTetris", [[new ApexUpgrade("Aircraft Armor Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(6, 530, 0, 50, "linaTetris", [[new ApexUpgrade("Aircraft Armor Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_va = [0,
    new ApexGeneral(1, 75, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5, 410, 0, 50, "linaTetris", [[new ApexUpgrade("Aircraft Armor Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(5, 485, 0, 50, "linaTetris", [[new ApexUpgrade("Aircraft Armor Enhancement", ["+1% HP", "+2% HP"], [2,2])]]),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_mistral = [0,
    new ApexGeneral(1, 75, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_balancer = [0,
    new ApexGeneral(1, 50, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_loyal = [0,
    new ApexGeneral(1, 90, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10, 990, 0, 0, "PremTech", [[new ApexUpgrade("Aircraft Armor Enhancement", ["+1% HP", "+2% HP", "+3% HP"], [2,2,2]), new ApexUpgrade("Enhance Recharge Power", ["+2% Pulse Cannon Damage"], [2])]]),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_v022 = [0,
    new ApexGeneral(1, 70, 0, 0, "linaTetris"),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];

var apex_rational = [0,
    new ApexGeneral(1),
    new ApexGeneral(2),
    new ApexGeneral(3),
    new ApexGeneral(4),
    new ApexGeneral(5),
    new ApexGeneral(6),
    new ApexGeneral(7),
    new ApexGeneral(8),
    new ApexGeneral(9),
    new ApexGeneral(10),
    new ApexGeneral(11),
    new ApexGeneral(12),
    new ApexGeneral(13),
    new ApexGeneral(14),
    new ApexGeneral(15),
    new ApexGeneral(16),
    new ApexGeneral(17),
    new ApexGeneral(18),
    new ApexGeneral(19),
    new ApexGeneral(20)
];